### ISSUE TITLE
Support for recurring tasks

### ISSUE THREAD

**Issue by noncomplete** [foobuzz/todo#20]
Is there a way to set a task as recurring? I checked the user guide and could not find anything about this.

**Comment by foobuzz** [comment]
Hey, unfortunately no, not at the moment at least. Do you have any specific idea in mind on how it could work?

**Comment by noncomplete** [comment]
It could simply be a list to save a task with the interval at which the task will recur. Maybe imagine a task like "Review class notes" that recurs every 3 days. The todo application could store the task alongside the date it was created and the increment value of time for recurring the task. After that, the application could just create a new task referring to the database of recurring tasks at set intervals.

Another option to add would be to recur a task from a set date. For example "Review class notes" task can be set to start at a later date with the `--start` flag and it can recur every 3 days.

These are just my opinions, I think there are better ways to implement them like [taskwarrior](https://taskwarrior.org/docs/recurrence.html) does. But I found your application simple enough to use in my daily life. Thank you for working on this.

**Comment by foobuzz** [comment]
Hey! I'm glad that you use and like `todo` :slightly_smiling_face: 

Thank you for the implementation ideas! Those are definitely good options to start it out. My question was more about the way it would work _as a feature_ though. As far as my usage of `todo` is concerned, I don't really have a need for recurring tasks myself, so it's important that I properly understand the need before going in any development. More specifically, I usually associate the notion of recurring task with the notion of notification, which is why I rather use a reminder app on my smart phone for such use-cases.

Anyway, assuming that if a task is supposed to recur every Monday and you invoke `todo` on a Tuesday, it would show the task that has recurred the day before, I wonder about the following questions:

 1. Where does this task appear? Should it appear among other tasks (maybe with a emoji or something to show that it comes from a recurrence) or should it appear in an "out-of-band" listing, maybe above all other tasks? If it appears among other tasks, I guess it should be sorted according to its added date, which would be "last monday", and maybe other properties inherited from the first task from which it was defined.
 2. What happens if you invoke `todo` on a Tuesday but 3 weeks later? Now the task has conceptually recurred 3 times, but at this point does it make sense to have 3 copies of the same task? Maybe we should consider that previous occurrences are now useless and we should only make the _last_ occurrence exist? Or maybe, on the contrary, we should consider that everything is blocked at the _first_ occurrence that is still undone?

I'm curious about your opinion on this, as you seem to have a specific use-case for this feature. Tell me what you think :)

**Comment by foobuzz** [comment]
Hey, I've added support for recurring tasks as documented [here](https://github.com/foobuzz/todo/blob/master/doc/guide.md#recurring-tasks). Don't hesitate to submit feedback in this issue, or open new issues for bugs. I'm closing this one for now.
