### ISSUE TITLE
Consider add autocomplete with `Tab`

### ISSUE THREAD

**Issue by imp0wd3r** [foobuzz/todo#6]
When I use `todo -d` to mark my task done, I want to use `Tab` to autocomplete, but something happened like this:
![screenshot from 2016-03-19 23 09 47](https://cloud.githubusercontent.com/assets/17606044/13899387/c22fa106-ee27-11e5-9665-2080a2fc494b.png)

To make this tool prettier,please consider to add this function into the project.

**Comment by foobuzz** [comment]
Hi imp0wd3r

It seems that your message lacks the example of what happens when you use Tab to autocomplete. You would like to autocomplete the "todo ..." or to autocomplete the ID of a task ? The former should be done by your shell by using your command history. The latter seems complicated to implement since when you're typing down the command, the program isn't running and it's the shell that decides how to autocomplete.

**Comment by foobuzz** [comment]
So for some reason I wasn't seeing the screenshot before. Now I see it. I cannot reproduce the behavior of the screenshot, but since another library is used for arguments parsing since v2, I doubt such behavior holds.

**Comment by foobuzz** [comment]
Bash completion is now available on version 2.1
