### ISSUE TITLE
YYYY-MM-DD HH:MM:SS format

### ISSUE THREAD

**Issue by Mahoor** [foobuzz/todo#8]
not passing YYYY-MM-DD HH:MM:SS format as a MOMENT argument because of the space between the date part and the time part.

**Comment by foobuzz** [comment]
Hello,

This is fixed in version 3.1.1

I realized that contrarily to what was specified in the documentation YYYY-MM-DD HH:MM:SS wasn't supported, but YYYY-MM-DDTHH:MM:SS was (the T in the middle comes from the ISO 8601 spec). I added support for the format with the space and documented the format with the T.

When you need to use arguments that contain space(s) in your terminal, you can either escape the space with \ or wrap the whole argument inside simple quotes.
